# Generated by Django 5.0.7 on 2024-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XAF', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='means',
            field=models.CharField(default='MOMO', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='number',
            field=models.IntegerField(default=652592011),
        ),
    ]
