# Generated by Django 5.0.7 on 2024-07-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_currency_payment_means_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(),
        ),
    ]
