# Generated by Django 5.0.7 on 2024-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
